# Generated by Django 4.1.13 on 2025-10-19 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roadmap_content', models.TextField(blank=True, help_text='AI-generated step-by-step plan for this career.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('keywords', models.TextField(help_text='Comma-separated list of keywords, skills, and interests related to this career.')),
                ('holland_code', models.CharField(blank=True, help_text='Primary 3-letter Holland Code for this career.', max_length=3, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Career Journey', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='A user-editable title for the session.', max_length=255, null=True)),
                ('context', models.TextField(blank=True, help_text='The user-provided context for the interview (e.g., job role, scholarship type).', null=True)),
                ('difficulty', models.CharField(choices=[('simple', 'Simple'), ('standard', 'Standard'), ('hard', 'Hard')], default='standard', max_length=10)),
                ('duration_minutes', models.IntegerField(default=3, help_text='The user-selected duration for the interview.')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the question appears.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/')),
                ('personality_type', models.CharField(blank=True, help_text="User's 3-letter Holland Code (e.g., RIA, SEC)", max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Must be in E.164 format, e.g., +14155238886', max_length=30, null=True, unique=True)),
                ('whatsapp_subscribed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityTestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('personality_code', models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='apps.personalitytestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tracked', models.BooleanField(default=False, help_text='User has marked this as a high-priority opportunity.')),
                ('title', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('JOB', 'Job'), ('SCHOLARSHIP', 'Scholarship'), ('INTERNSHIP', 'Internship'), ('GRANT', 'Grant'), ('OTHER', 'Other')], default='JOB', max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('source_url', models.URLField(max_length=512)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='apps.actionplan')),
            ],
            options={
                'ordering': ['-found_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text="Order of the folder in the user's list.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='apps.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='A score from 0 to 100.')),
                ('confidence_score', models.IntegerField(help_text='A score from 0 to 100 reflecting vocal confidence.')),
                ('clarity_score', models.IntegerField(help_text='A score from 0 to 100 for speech clarity.')),
                ('camera_presence_score', models.IntegerField(default=0, help_text='A score from 0 to 100 based on camera presence.')),
                ('feedback_summary', models.TextField(help_text='AI-generated summary and suggestions for improvement.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='apps.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnalysisPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('person_detected', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_points', to='apps.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=4)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apps.careerjourney')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='careerjourney',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='apps.journeyfolder'),
        ),
        migrations.AddField(
            model_name='careerjourney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_journeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='apps.career'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPersonalityTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.personalitytestchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.personalitytestquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='actionplan',
            unique_together={('user', 'career')},
        ),
    ]
